name: Code Review GPT

on:
  pull_request:
    branches: [main]

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    environment: OPENAI_API_KEY
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.1.10
        with:
          OPENAI_API_KEY: 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
          MODEL: 'gpt-4o'
          GITHUB_TOKEN: ${{ github.token }}
