
name: Code Review GPT

on:
  pull_request:
    branches: [main]

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.1.10
        with:
          OPENAI_API_KEY: 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
          MODEL: 'gpt-4o'
          GITHUB_TOKEN: ${{ github.token }}
